- hosts: all
  gather_facts: yes
  become: yes
  become_user: root
  tasks:

    - name: Create a Volume Group
      community.general.lvg:
        vg: testvg
        pvs: /dev/xvdh
        pesize: 19G
      

    - name: Create a logical volume of 512m
      community.general.lvol:
        vg: testvg
        lv: testlv
        size: 18G

    - name: Create a directory /test
      file:
        path: /test
        state: directory
      become: yes
      become_user: root

    - name: Fetch the UUID for LV partition
      command: blkid -s UUID -o value /dev/xvdh
      changed_when: false
      register: blkid_out

    - name: Format the partition to xfs
      command: sudo mkfs.ext4 /dev/testvg/testlv

    - name: Add the entry to fstab
      command: echo 'UUID={{ blkid_out.stdout }} /test ext4 defaults 0 0' >> /etc/fstab
      become: yes

    - name: Mount the LV on the /test
      mount:
        path: /test
        src: /dev/testvg/testlv
        fstype: ext4
        state: mounted
    
