---

name: update galaxy

on:
    push:
        branches:
            - main
jobs:
    update_role:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: robertdebock/galaxy-action@master
              with:
                  galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
                  git_branch: main
